#!/usr/bin/env bash
# Acceptance Test: Workload Setup installs operator Routes, ACME wants, uniqueness (#52)
set -euo pipefail
# shellcheck source=lib.sh
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_ip
acceptance_ssh_opts
[[ -n "${REPO_ROOT:-}" ]] || fail "fixture missing REPO_ROOT (run via ./test.sh)"

FIX_DIR="$(mktemp -d)"
trap 'rm -rf "${FIX_DIR}"' EXIT

mkdir -p "${FIX_DIR}/alpha/routes"
cat >"${FIX_DIR}/alpha/manifest.json" <<'EOF'
{
  "name": "alpha",
  "intent": "run",
  "public_hostnames": ["alpha.example.test"],
  "upstream": "alpha:8080"
}
EOF
cat >"${FIX_DIR}/alpha/routes/http.conf" <<'EOF'
# operator-authored Route for alpha
server {
    listen 80;
    listen [::]:80;
    server_name alpha.example.test;
    location / { return 404; }
}
EOF

cat >"${FIX_DIR}/beta.json" <<'EOF'
{
  "name": "beta",
  "intent": "run",
  "public_hostnames": ["alpha.example.test"],
  "upstream": "beta:8080"
}
EOF

mkdir -p "${FIX_DIR}/zero"
cat >"${FIX_DIR}/zero/manifest.json" <<'EOF'
{
  "name": "zero",
  "intent": "run",
  "public_hostnames": ["zero.example.test"],
  "upstream": "zero:8080"
}
EOF

# Clean durable leftovers
ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "rm -rf /var/lib/prefect/components_data/workloads/alpha \
          /var/lib/prefect/components_data/workloads/beta \
          /var/lib/prefect/components_data/workloads/zero \
          /var/lib/prefect/components_data/edge/routes/alpha.conf \
          /var/lib/prefect/components_data/edge/routes/alpha--* \
          /var/lib/prefect/components_data/edge/routes/zero--* \
          /var/lib/prefect/components_data/edge/claims/alpha.example.test \
          /var/lib/prefect/components_data/edge/claims/zero.example.test"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/alpha/manifest.json"

sot="$(ssh "${SSH_OPTS[@]}" "root@${IP}" "cat /var/lib/prefect/components_data/workloads/alpha/routes/http.conf")"
echo "${sot}" | grep -q 'operator-authored Route for alpha' \
  || fail "Route SoT not stored under workloads/alpha/routes/"
installed="$(ssh "${SSH_OPTS[@]}" "root@${IP}" "cat /var/lib/prefect/components_data/edge/routes/alpha--http.conf")"
[[ "${installed}" == "${sot}" ]] || fail "installed Route bytes must match operator SoT"
echo "${installed}" | grep -q 'Generated by Prefect' \
  && fail "Prefect must not generate Route shells" || true
! ssh "${SSH_OPTS[@]}" "root@${IP}" "test -f /var/lib/prefect/components_data/workloads/alpha/interior.conf" \
  || fail "interior.conf must not be stored"
claim="$(ssh "${SSH_OPTS[@]}" "root@${IP}" "cat /var/lib/prefect/components_data/edge/claims/alpha.example.test")"
[[ "${claim}" == "alpha" ]] || fail "claim expected alpha, got '${claim}'"
want="$(ssh "${SSH_OPTS[@]}" "root@${IP}" "cat /var/lib/prefect/components_data/edge/acme/want-list")"
echo "${want}" | grep -qx 'alpha.example.test' \
  || fail "ACME want-list missing alpha.example.test (got: ${want})"
pass "Workload Setup installs operator Route, claim, and ACME want-list"

set +e
"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/beta.json" >/tmp/beta-setup.out 2>&1
beta_rc=$?
set -e
if [[ ${beta_rc} -eq 0 ]]; then
  fail "expected uniqueness failure when beta claims alpha.example.test"
fi
grep -qi 'already claimed\|conflict\|unique' /tmp/beta-setup.out \
  || fail "uniqueness failure did not mention claim conflict (output: $(cat /tmp/beta-setup.out))"
pass "Workload Setup fails when Public Hostname is already claimed by Intent run"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/zero/manifest.json"
zero_installed="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "ls /var/lib/prefect/components_data/edge/routes/zero--* 2>/dev/null || true")"
[[ -z "${zero_installed}" ]] || fail "zero-Route Workload must not install Edge Route files (got: ${zero_installed})"
ssh "${SSH_OPTS[@]}" "root@${IP}" "test -f /var/lib/prefect/components_data/workloads/zero/manifest.json" \
  || fail "zero-Route Workload Manifest should still be stored"
pass "Workload Setup succeeds with Intent run and no routes/ directory"

code=""
for _ in $(seq 1 30); do
  code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 10 --max-time 15 \
    -H 'Host: alpha.example.test' "http://${IP}/" 2>/dev/null || true)"
  [[ "${code}" == "404" ]] && break
  sleep 1
done
[[ "${code}" == "404" ]] || fail "operator Route without cert: expected HTTP 404, got '${code}'"
pass "Workload Setup succeeds without waiting for certificate issuance"
