#!/usr/bin/env bash
# Acceptance Test: thin Manifest + operator Routes/Quadlets (ADR-0024 / #57 / ADR-0028)
set -euo pipefail
# shellcheck source=lib.sh
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_ip
acceptance_ssh_opts
[[ -n "${REPO_ROOT:-}" ]] || fail "fixture missing REPO_ROOT (run via ./test.sh)"

FIX_DIR="$(mktemp -d)"
trap 'rm -rf "${FIX_DIR}"' EXIT

ROUTE_FQDN="$(acceptance_route_fqdn)"

mkdir -p "${FIX_DIR}/alpha/quadlets"
cat >"${FIX_DIR}/alpha/manifest.json" <<'EOF'
{
  "intent": "run",
  "description": "alpha probe — ignored by automation"
}
EOF
if [[ -n "${ROUTE_FQDN}" ]]; then
  mkdir -p "${FIX_DIR}/alpha/routes"
  cat >"${FIX_DIR}/alpha/routes/${ROUTE_FQDN}.conf" <<EOF
# operator-authored Route fragment for alpha (${ROUTE_FQDN})
location = /alpha-route-probe {
    default_type text/plain;
    return 200 'alpha-route-ok';
}
EOF
fi

mkdir -p "${FIX_DIR}/legacy/routes"
cat >"${FIX_DIR}/legacy/manifest.json" <<'EOF'
{
  "intent": "run",
  "public_hostnames": ["legacy.example.test"]
}
EOF

mkdir -p "${FIX_DIR}/named"
cat >"${FIX_DIR}/named/manifest.json" <<'EOF'
{
  "name": "named",
  "intent": "run"
}
EOF

mkdir -p "${FIX_DIR}/upstreamed"
cat >"${FIX_DIR}/upstreamed/manifest.json" <<'EOF'
{
  "intent": "run",
  "upstream": "upstreamed:8080"
}
EOF

mkdir -p "${FIX_DIR}/sourced"
cat >"${FIX_DIR}/sourced/manifest.json" <<'EOF'
{
  "intent": "run",
  "source": "https://example.test/bundle.tar"
}
EOF

mkdir -p "${FIX_DIR}/zero"
cat >"${FIX_DIR}/zero/manifest.json" <<'EOF'
{
  "intent": "run"
}
EOF

mkdir -p "${FIX_DIR}/clash/quadlets"
cat >"${FIX_DIR}/clash/manifest.json" <<'EOF'
{
  "intent": "run"
}
EOF
# Collide with Component unit basename already on the Host.
cat >"${FIX_DIR}/clash/quadlets/edge-nginx.container" <<'EOF'
[Unit]
Description=clash should fail

[Container]
Image=docker.io/library/nginx:alpine
ContainerName=clash
Network=service-network.network

[Service]
Restart=on-failure

[Install]
WantedBy=default.target
EOF

mkdir -p "${FIX_DIR}/owner-a/quadlets" "${FIX_DIR}/owner-b/quadlets"
cat >"${FIX_DIR}/owner-a/manifest.json" <<'EOF'
{ "intent": "run" }
EOF
cat >"${FIX_DIR}/owner-b/manifest.json" <<'EOF'
{ "intent": "run" }
EOF
cat >"${FIX_DIR}/owner-a/quadlets/shared-name.container" <<'EOF'
[Unit]
Description=owner-a claims shared-name

[Container]
Image=docker.io/library/nginx:alpine
ContainerName=shared-name-a
Network=service-network.network

[Service]
Restart=on-failure

[Install]
WantedBy=default.target
EOF
cp "${FIX_DIR}/owner-a/quadlets/shared-name.container" "${FIX_DIR}/owner-b/quadlets/shared-name.container"

# Snapshot Domain want-list (must not change across Workload Setup).
want_before="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "cat /var/lib/prefect/components_data/edge/acme/want-list 2>/dev/null || true")"

# Clean durable leftovers
ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "rm -rf /var/lib/prefect/components_data/workloads/alpha \
          /var/lib/prefect/components_data/workloads/legacy \
          /var/lib/prefect/components_data/workloads/named \
          /var/lib/prefect/components_data/workloads/upstreamed \
          /var/lib/prefect/components_data/workloads/sourced \
          /var/lib/prefect/components_data/workloads/zero \
          /var/lib/prefect/components_data/workloads/clash \
          /var/lib/prefect/components_data/workloads/owner-a \
          /var/lib/prefect/components_data/workloads/owner-b \
          /var/lib/prefect/components_data/edge/routes/alpha.conf \
          /var/lib/prefect/components_data/edge/routes/alpha--* \
          /var/lib/prefect/components_data/edge/routes/zero--* \
          /var/lib/prefect/components_data/edge/routes/clash--*; \
   rm -f /home/prefect/.config/containers/systemd/alpha.container \
         /home/prefect/.config/containers/systemd/zero.container \
         /home/prefect/.config/containers/systemd/legacy.container \
         /home/prefect/.config/containers/systemd/shared-name.container"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/alpha/manifest.json"

if [[ -n "${ROUTE_FQDN}" ]]; then
  sot="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
    "cat /var/lib/prefect/components_data/workloads/alpha/routes/${ROUTE_FQDN}.conf")"
  echo "${sot}" | grep -q 'operator-authored Route fragment for alpha' \
    || fail "Route SoT not stored under workloads/alpha/routes/"
  installed="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
    "cat /var/lib/prefect/components_data/edge/routes/alpha--${ROUTE_FQDN}.conf")"
  [[ "${installed}" == "${sot}" ]] || fail "installed Route bytes must match operator SoT"
  echo "${installed}" | grep -q 'Generated by Prefect' \
    && fail "Prefect must not generate Route shells" || true
  pass "Workload Setup installs operator Route fragment; thin Manifest; no invented Quadlet"
else
  echo "SOFT-SKIP: empty Domain want-list — Route install assertions (ADR-0028)"
fi

! ssh "${SSH_OPTS[@]}" "root@${IP}" "test -f /var/lib/prefect/components_data/workloads/alpha/interior.conf" \
  || fail "interior.conf must not be stored"
# No Prefect-minted Quadlet when quadlets/ is empty.
alpha_units="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "ls /home/prefect/.config/containers/systemd/alpha.container 2>/dev/null || true")"
[[ -z "${alpha_units}" ]] || fail "empty quadlets/ must not invent a Quadlet (got: ${alpha_units})"
pass "thin Manifest; no invented Quadlet"

want_after="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "cat /var/lib/prefect/components_data/edge/acme/want-list 2>/dev/null || true")"
[[ "${want_after}" == "${want_before}" ]] \
  || fail "Workload Setup must not rewrite ACME want-list (before='${want_before}' after='${want_after}')"
pass "Workload Setup leaves Domain ACME want-list unchanged"

reject_thick() {
  local label="$1"
  local path="$2"
  local needle="$3"
  set +e
  "${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${path}" >/tmp/thick-setup.out 2>&1
  local rc=$?
  set -e
  [[ ${rc} -ne 0 ]] || fail "expected failure for ${label}"
  grep -qi "${needle}" /tmp/thick-setup.out \
    || fail "${label} rejection did not mention ${needle} (output: $(cat /tmp/thick-setup.out))"
}

reject_thick "public_hostnames" "${FIX_DIR}/legacy/manifest.json" "public_hostnames\|unknown keys\|allowlist"
reject_thick "name" "${FIX_DIR}/named/manifest.json" "name\|unknown keys\|allowlist"
reject_thick "upstream" "${FIX_DIR}/upstreamed/manifest.json" "upstream\|unknown keys\|allowlist"
reject_thick "source" "${FIX_DIR}/sourced/manifest.json" "source\|unknown keys\|allowlist"
pass "Workload Setup rejects thick Manifest keys (ADR-0024 allowlist)"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/zero/manifest.json"
zero_installed="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "ls /var/lib/prefect/components_data/edge/routes/zero--* 2>/dev/null || true")"
[[ -z "${zero_installed}" ]] || fail "zero-Route Workload must not install Edge Route files (got: ${zero_installed})"
ssh "${SSH_OPTS[@]}" "root@${IP}" "test -f /var/lib/prefect/components_data/workloads/zero/manifest.json" \
  || fail "zero-Route Workload Manifest should still be stored"
pass "Workload Setup succeeds with Intent run and no routes/ directory"

set +e
"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/clash/manifest.json" >/tmp/clash-setup.out 2>&1
clash_rc=$?
set -e
[[ ${clash_rc} -ne 0 ]] || fail "expected failure when quadlet basename collides with Component unit"
grep -qi 'edge-nginx\|already exists\|not owned' /tmp/clash-setup.out \
  || fail "collision rejection unclear (output: $(cat /tmp/clash-setup.out))"
pass "Workload Setup refuses Quadlet basename colliding with Component unit"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/owner-a/manifest.json"
set +e
"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/owner-b/manifest.json" >/tmp/owner-b-setup.out 2>&1
owner_b_rc=$?
set -e
[[ ${owner_b_rc} -ne 0 ]] || fail "expected failure when second Workload claims same quadlet basename"
grep -qi 'shared-name\|already exists\|not owned' /tmp/owner-b-setup.out \
  || fail "cross-Workload collision unclear (output: $(cat /tmp/owner-b-setup.out))"
pass "Workload Setup refuses Quadlet basename claimed by another Workload"
