#!/usr/bin/env bash
# Acceptance Test: ACME after PEMs does not rewrite operator Routes; Edge may reload
# (ADR-0022 / ADR-0028). Soft-skips when Domain want-list is empty.
set -euo pipefail
# shellcheck source=lib.sh
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_ip
acceptance_host_session
[[ -n "${REPO_ROOT:-}" ]] || fail "fixture missing REPO_ROOT (run via ./test.sh)"

HOST="$(acceptance_route_fqdn)"
if [[ -z "${HOST}" ]]; then
  echo "SOFT-SKIP: empty Domain want-list — no FQDN for ACME Route-refresh probe"
  exit 0
fi

WL="acme-refresh"
FIX_DIR="$(mktemp -d)"
trap 'rm -rf "${FIX_DIR}"' EXIT

mkdir -p "${FIX_DIR}/${WL}/routes"
cat >"${FIX_DIR}/${WL}/manifest.json" <<EOF
{
  "intent": "run"
}
EOF
MARKER="# operator-route-marker-${WL}"
cat >"${FIX_DIR}/${WL}/routes/${HOST}.conf" <<EOF
${MARKER}
location = /acme-refresh-probe {
    default_type text/plain;
    return 200 'acme-refresh-ok';
}
EOF

host_ssh \
  "rm -rf /var/lib/prefect/components_data/edge/routes/${WL}.conf \
          /var/lib/prefect/components_data/edge/routes/${WL}--* \
          /var/lib/prefect/components_data/workloads/${WL}"

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/${WL}/manifest.json"

route_before="$(host_ssh \
  "cat /var/lib/prefect/components_data/edge/routes/${WL}--${HOST}.conf")"
echo "${route_before}" | grep -q "${MARKER}" \
  || fail "operator Route marker missing before ACME"
pass "Operator Route fragment installed before ACME"

host_ssh bash -s <<REMOTE
set -euo pipefail
UID_NUM="\$(id -u prefect)"
export XDG_RUNTIME_DIR="/run/user/\${UID_NUM}"
systemctl start "user@\${UID_NUM}.service"
runuser -u prefect -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" \
  systemctl --user stop edge-acme.service 2>/dev/null || true
runuser -u prefect -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" PREFECT_ACME_ISSUE=0 \
  /var/lib/prefect/components/edge/acme-run.sh
REMOTE

route_after="$(host_ssh \
  "cat /var/lib/prefect/components_data/edge/routes/${WL}--${HOST}.conf")"
[[ "${route_after}" == "${route_before}" ]] \
  || fail "ACME must not rewrite operator Route file contents"
echo "${route_after}" | grep -q 'Generated by Prefect' \
  && fail "ACME must not inject projected Route shells" || true
pass "ACME oneshot leaves operator Route bytes unchanged"
