#!/usr/bin/env bash
# Acceptance Test: ACME after PEMs does not rewrite operator Routes; Edge may reload (#52)
# Uses fixture PEMs + PREFECT_ACME_ISSUE=0 (no live CA / public domain).
set -euo pipefail
# shellcheck source=lib.sh
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_ip
acceptance_ssh_opts
[[ -n "${REPO_ROOT:-}" ]] || fail "fixture missing REPO_ROOT (run via ./test.sh)"

HOST="acme-refresh.example.test"
WL="acme-refresh"
FIX_DIR="$(mktemp -d)"
trap 'rm -rf "${FIX_DIR}"' EXIT

mkdir -p "${FIX_DIR}/routes"
cat >"${FIX_DIR}/manifest.json" <<EOF
{
  "name": "${WL}",
  "intent": "run",
  "public_hostnames": ["${HOST}"],
  "upstream": "${WL}:80"
}
EOF
MARKER="# operator-route-marker-${WL}"
cat >"${FIX_DIR}/routes/https.conf" <<EOF
${MARKER}
server {
    listen 80;
    listen [::]:80;
    server_name ${HOST};
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme;
        default_type text/plain;
    }
    location / {
        return 301 https://\$host\$request_uri;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${HOST};
    ssl_certificate     /etc/nginx/certs/${HOST}/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/${HOST}/privkey.pem;
    location / {
        return 200 'acme-refresh-ok';
        add_header Content-Type text/plain;
    }
}
EOF

ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "rm -rf /var/lib/prefect/components_data/edge/certs/${HOST} \
          /var/lib/prefect/components_data/edge/routes/${WL}.conf \
          /var/lib/prefect/components_data/edge/routes/${WL}--* \
          /var/lib/prefect/components_data/workloads/${WL}"

# Plant PEMs before operator Route that references ssl_certificate paths.
ssh "${SSH_OPTS[@]}" "root@${IP}" bash -s <<REMOTE
set -euo pipefail
CERT_DIR=/var/lib/prefect/components_data/edge/certs/${HOST}
mkdir -p "\${CERT_DIR}"
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout "\${CERT_DIR}/privkey.pem" \
  -out "\${CERT_DIR}/fullchain.pem" \
  -days 2 -subj "/CN=${HOST}" >/dev/null 2>&1
chown -R prefect:prefect /var/lib/prefect/components_data/edge/certs
REMOTE

"${REPO_ROOT}/prefect/workload-setup.sh" --env "${PREFECT_ENV:-test}" "${FIX_DIR}/manifest.json"

route_before="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "cat /var/lib/prefect/components_data/edge/routes/${WL}--https.conf")"
echo "${route_before}" | grep -q "${MARKER}" \
  || fail "operator Route marker missing before ACME"
pass "Operator Route installed before ACME"

# ACME must not rewrite Route files; reload only.
ssh "${SSH_OPTS[@]}" "root@${IP}" bash -s <<REMOTE
set -euo pipefail
UID_NUM="\$(id -u prefect)"
export XDG_RUNTIME_DIR="/run/user/\${UID_NUM}"
systemctl start "user@\${UID_NUM}.service"
runuser -u prefect -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" \
  systemctl --user stop edge-acme.service 2>/dev/null || true
runuser -u prefect -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" PREFECT_ACME_ISSUE=0 \
  /var/lib/prefect/components/edge/acme-run.sh
REMOTE

route_after="$(ssh "${SSH_OPTS[@]}" "root@${IP}" \
  "cat /var/lib/prefect/components_data/edge/routes/${WL}--https.conf")"
[[ "${route_after}" == "${route_before}" ]] \
  || fail "ACME must not rewrite operator Route file contents"
echo "${route_after}" | grep -q 'Generated by Prefect' \
  && fail "ACME must not inject projected Route shells" || true
pass "ACME oneshot leaves operator Route bytes unchanged"

tls_code=""
for _ in $(seq 1 30); do
  tls_code="$(curl -skS -o /dev/null -w '%{http_code}' --connect-timeout 10 --max-time 15 \
    --resolve "${HOST}:443:${IP}" "https://${HOST}/" 2>/dev/null || true)"
  [[ "${tls_code}" =~ ^[0-9]{3}$ ]] && break
  sleep 1
done
[[ "${tls_code}" =~ ^[1-5][0-9]{2}$ ]] || fail "TLS to ${HOST} failed after ACME reload (code='${tls_code}')"
pass "HTTPS live after ACME reload without Route rewrite (HTTP ${tls_code})"

redir_code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 10 --max-time 15 \
  -H "Host: ${HOST}" "http://${IP}/")"
[[ "${redir_code}" == "301" || "${redir_code}" == "302" ]] \
  || fail "expected :80 redirect after ACME reload, got HTTP ${redir_code}"
pass ":80 redirects to HTTPS after ACME reload"
