#!/usr/bin/env bash
# Project Edge Routes from every stored Workload Manifest on the Host Volume.
# Sourced by Workload Setup and Edge ACME (not an operator entrypoint).
# Expects: EDGE_DATA, WORKLOADS_ROOT, ROUTES_DIR (and CERTS_DIR derived from EDGE_DATA).
# Optional: USER_NAME for ownership; when sourced after quadlet_user_session_begin,
#           edge_reload_front_door restarts edge-pod if active.
#
# Sets EDGE_ROUTES_CHANGED=1 when projected Route file contents changed; else 0.

edge_project_routes_from_manifests() {
  local CERTS_DIR="${EDGE_DATA}/certs"
  local wl_dir manifest route_file
  local WL_NAME WL_INTENT WL_UPSTREAM WL_HOSTS WL_INTERIOR
  local host cert_dir cert_pem key_pem
  local routes_before routes_after

  mkdir -p "${ROUTES_DIR}" "${CERTS_DIR}"
  EDGE_ROUTES_CHANGED=0

  if compgen -G "${ROUTES_DIR}/*.conf" >/dev/null; then
    routes_before="$(cat "${ROUTES_DIR}"/*.conf | sha256sum)"
  else
    routes_before="none"
  fi

  if [[ ! -d "${WORKLOADS_ROOT}" ]]; then
    return 0
  fi

  for wl_dir in "${WORKLOADS_ROOT}"/*; do
    [[ -d "${wl_dir}" && -f "${wl_dir}/manifest.json" ]] || continue
    manifest="${wl_dir}/manifest.json"
    eval "$(python3 - "${manifest}" <<'PY'
import json, shlex, sys
m = json.load(open(sys.argv[1]))
name = m.get("name")
intent = m.get("intent")
upstream = m.get("upstream")
hosts = m.get("public_hostnames") or []
if not name or not isinstance(name, str):
    raise SystemExit("stored manifest.name must be a non-empty string")
if intent not in ("run", "stop", "trash"):
    raise SystemExit(f"stored manifest.intent must be run|stop|trash (got {intent!r})")
if not upstream or not isinstance(upstream, str):
    raise SystemExit("stored manifest.upstream must be a non-empty string")
if not isinstance(hosts, list) or not hosts or not all(isinstance(h, str) and h for h in hosts):
    raise SystemExit("stored manifest.public_hostnames must be a non-empty list of strings")
print(f"WL_NAME={shlex.quote(name)}")
print(f"WL_INTENT={shlex.quote(intent)}")
print(f"WL_UPSTREAM={shlex.quote(upstream)}")
print(f"WL_HOSTS={shlex.quote(' '.join(hosts))}")
PY
)"
    route_file="${ROUTES_DIR}/${WL_NAME}.conf"
    WL_INTERIOR="${wl_dir}/interior.conf"
    if [[ "${WL_INTENT}" == "trash" ]]; then
      rm -f "${route_file}"
      continue
    fi
    {
      echo "# Generated by Prefect Edge Route projection for '${WL_NAME}' — do not edit."
      echo "# Upstream: ${WL_UPSTREAM}"
      for host in ${WL_HOSTS}; do
        cert_dir="${CERTS_DIR}/${host}"
        cert_pem="${cert_dir}/fullchain.pem"
        key_pem="${cert_dir}/privkey.pem"
        echo
        echo "server {"
        echo "    listen 80;"
        echo "    listen [::]:80;"
        echo "    server_name ${host};"
        echo
        echo "    location ^~ /.well-known/acme-challenge/ {"
        echo "        root /var/www/acme;"
        echo "        default_type text/plain;"
        echo "    }"
        echo
        if [[ -f "${cert_pem}" && -f "${key_pem}" ]]; then
          echo "    location / {"
          echo "        return 301 https://\$host\$request_uri;"
          echo "    }"
        else
          echo "    location / {"
          echo "        # No certificate yet — no cleartext Workload proxy (ADR-0012 / ADR-0013)."
          echo "        return 404;"
          echo "    }"
        fi
        echo "}"
        if [[ -f "${cert_pem}" && -f "${key_pem}" ]]; then
          echo
          echo "server {"
          echo "    listen 443 ssl;"
          echo "    listen [::]:443 ssl;"
          echo "    server_name ${host};"
          echo "    ssl_certificate     /etc/nginx/certs/${host}/fullchain.pem;"
          echo "    ssl_certificate_key /etc/nginx/certs/${host}/privkey.pem;"
          echo
          if [[ "${WL_INTENT}" == "stop" ]]; then
            echo "    location / {"
            echo "        return 503;"
            echo "    }"
          elif [[ -f "${WL_INTERIOR}" ]]; then
            sed 's/^/    /' "${WL_INTERIOR}"
          else
            echo "    location / {"
            echo "        proxy_pass http://${WL_UPSTREAM};"
            echo "        proxy_set_header Host \$host;"
            echo "        proxy_set_header X-Forwarded-Proto https;"
            echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
            echo "    }"
          fi
          echo "}"
        fi
      done
    } >"${route_file}"
  done

  if [[ -n "${USER_NAME:-}" ]]; then
    chown -R "${USER_NAME}:${USER_NAME}" "${ROUTES_DIR}" "${CERTS_DIR}" 2>/dev/null || true
  fi

  if compgen -G "${ROUTES_DIR}/*.conf" >/dev/null; then
    routes_after="$(cat "${ROUTES_DIR}"/*.conf | sha256sum)"
  else
    routes_after="none"
  fi
  if [[ "${routes_before}" != "${routes_after}" ]]; then
    EDGE_ROUTES_CHANGED=1
  fi
}

edge_reload_front_door() {
  local user="${USER_NAME:-prefect}"
  local runtime="${XDG_RUNTIME_DIR:-/run/user/$(id -u "${user}" 2>/dev/null || id -u)}"
  local -a cmd
  local _ code

  if [[ "$(id -un)" == "${user}" ]]; then
    cmd=(env "XDG_RUNTIME_DIR=${runtime}" systemctl --user)
  elif declare -F quadlet_user >/dev/null 2>&1; then
    cmd=(quadlet_user systemctl --user)
  else
    return 0
  fi

  if "${cmd[@]}" --quiet is-active edge-pod.service; then
    "${cmd[@]}" restart edge-pod.service
    "${cmd[@]}" --quiet is-active edge-pod.service
    for _ in $(seq 1 30); do
      code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 3 http://127.0.0.1/ 2>/dev/null || true)"
      if [[ "${code}" =~ ^[0-9]{3}$ ]]; then
        return 0
      fi
      sleep 1
    done
    echo "edge_reload_front_door: Edge did not answer on :80 after restart" >&2
    return 1
  fi
}

# Reload Edge only when Route projection changed (avoids bouncing :80/:443 on no-op ACME runs).
edge_reload_front_door_if_routes_changed() {
  if [[ "${EDGE_ROUTES_CHANGED:-0}" == "1" ]]; then
    edge_reload_front_door
  fi
}
