#!/usr/bin/env bash
# Host-local Workload Setup. Invoked by prefect/workload-setup.sh (not an operator entrypoint).
# Usage: PREFECT_USER=prefect bash workload-setup-host.sh /path/to/staging-dir
# Staging dir must contain manifest.json and optionally interior.conf.
set -euo pipefail

STAGE="${1:?staging dir required}"
USER_NAME="${PREFECT_USER:-prefect}"
MANIFEST="${STAGE}/manifest.json"
INTERIOR_SRC="${STAGE}/interior.conf"

DATA_ROOT=/var/lib/prefect/components_data
EDGE_DATA="${DATA_ROOT}/edge"
WORKLOADS_ROOT="${DATA_ROOT}/workloads"
CLAIMS_DIR="${EDGE_DATA}/claims"
ROUTES_DIR="${EDGE_DATA}/routes"
ACME_DIR="${EDGE_DATA}/acme"
WANT_LIST="${ACME_DIR}/want-list"

# shellcheck source=quadlet-user-session.sh
source /var/lib/prefect/components/lib/quadlet-user-session.sh

[[ -f "${MANIFEST}" ]] || {
  echo "manifest.json missing in ${STAGE}" >&2
  exit 1
}

command -v python3 >/dev/null || {
  echo "python3 required on Host for Workload Manifest parsing" >&2
  exit 1
}

eval "$(python3 - "${MANIFEST}" <<'PY'
import json, shlex, sys
m = json.load(open(sys.argv[1]))
name = m.get("name")
state = m.get("state")
upstream = m.get("upstream")
hosts = m.get("public_hostnames") or []
if not name or not isinstance(name, str):
    raise SystemExit("manifest.name must be a non-empty string")
if state not in ("running", "stopped", "trashed"):
    raise SystemExit("manifest.state must be running|stopped|trashed")
if not upstream or not isinstance(upstream, str):
    raise SystemExit("manifest.upstream must be a non-empty string (host:port)")
if not isinstance(hosts, list) or not hosts or not all(isinstance(h, str) and h for h in hosts):
    raise SystemExit("manifest.public_hostnames must be a non-empty list of strings")
if any(c in name for c in "/ \t\n"):
    raise SystemExit("manifest.name must be a single path segment")
print(f"WL_NAME={shlex.quote(name)}")
print(f"WL_STATE={shlex.quote(state)}")
print(f"WL_UPSTREAM={shlex.quote(upstream)}")
print(f"WL_HOSTS={shlex.quote(' '.join(hosts))}")
PY
)"

mkdir -p "${CLAIMS_DIR}" "${ROUTES_DIR}" "${ACME_DIR}" "${WORKLOADS_ROOT}/${WL_NAME}"
[[ -f "${WANT_LIST}" ]] || : >"${WANT_LIST}"

# Reject interior that tries to own Public Hostnames / listen / TLS.
if [[ -f "${INTERIOR_SRC}" ]]; then
  if grep -Eiq '^\s*(server_name|listen|ssl_certificate|ssl_certificate_key)\b' "${INTERIOR_SRC}"; then
    echo "Workload interior must not declare server_name, listen, or TLS certificate directives" >&2
    exit 1
  fi
fi

# Uniqueness among running/stopped claimants (trashed releases names).
if [[ "${WL_STATE}" == "trashed" ]]; then
  :
else
  for host in ${WL_HOSTS}; do
    claim_file="${CLAIMS_DIR}/${host}"
    if [[ -f "${claim_file}" ]]; then
      owner="$(cat "${claim_file}")"
      if [[ "${owner}" != "${WL_NAME}" ]]; then
        echo "Public Hostname '${host}' is already claimed by Workload '${owner}' (conflict)" >&2
        exit 1
      fi
    fi
  done
fi

# Drop prior claims owned by this Workload, then re-apply if still claiming.
if [[ -d "${CLAIMS_DIR}" ]]; then
  for claim_file in "${CLAIMS_DIR}"/*; do
    [[ -f "${claim_file}" ]] || continue
    if [[ "$(cat "${claim_file}")" == "${WL_NAME}" ]]; then
      rm -f "${claim_file}"
    fi
  done
fi

if [[ "${WL_STATE}" != "trashed" ]]; then
  for host in ${WL_HOSTS}; do
    printf '%s\n' "${WL_NAME}" >"${CLAIMS_DIR}/${host}"
  done
fi

install -m 0644 "${MANIFEST}" "${WORKLOADS_ROOT}/${WL_NAME}/manifest.json"
if [[ -f "${INTERIOR_SRC}" ]]; then
  install -m 0644 "${INTERIOR_SRC}" "${WORKLOADS_ROOT}/${WL_NAME}/interior.conf"
else
  rm -f "${WORKLOADS_ROOT}/${WL_NAME}/interior.conf"
fi

ROUTE_FILE="${ROUTES_DIR}/${WL_NAME}.conf"
if [[ "${WL_STATE}" == "trashed" ]]; then
  rm -f "${ROUTE_FILE}"
else
  {
    echo "# Generated by Workload Setup for '${WL_NAME}' — do not edit."
    echo "# Upstream: ${WL_UPSTREAM}"
    echo "server {"
    echo "    listen 80;"
    echo "    listen [::]:80;"
    echo "    server_name ${WL_HOSTS};"
    echo
    echo "    location ^~ /.well-known/acme-challenge/ {"
    echo "        root /var/www/acme;"
    echo "        default_type text/plain;"
    echo "    }"
    echo
    echo "    location / {"
    echo "        # Cleartext Workload proxy is forbidden (ADR-0013); HTTPS shell when cert exists."
    echo "        return 404;"
    echo "    }"
    echo "}"
  } >"${ROUTE_FILE}"
fi

# Rebuild ACME want-list from running claimants only (ADR-0014 / ADR-0015).
: >"${WANT_LIST}.tmp"
if [[ -d "${WORKLOADS_ROOT}" ]]; then
  for wl_dir in "${WORKLOADS_ROOT}"/*; do
    [[ -d "${wl_dir}" && -f "${wl_dir}/manifest.json" ]] || continue
    python3 - "${wl_dir}/manifest.json" "${WANT_LIST}.tmp" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))
if m.get("state") != "running":
    raise SystemExit(0)
path = sys.argv[2]
with open(path, "a") as f:
    for h in m.get("public_hostnames") or []:
        f.write(f"{h}\n")
PY
  done
fi
sort -u "${WANT_LIST}.tmp" -o "${WANT_LIST}"
rm -f "${WANT_LIST}.tmp"

chown -R "${USER_NAME}:${USER_NAME}" "${DATA_ROOT}"

quadlet_user_session_begin
quadlet_user_session_reload
# Pick up projected Routes from the bind-mounted routes dir; do not wait for ACME.
if quadlet_user systemctl --user --quiet is-active edge-pod.service; then
  quadlet_user systemctl --user restart edge-pod.service
  quadlet_user systemctl --user --quiet is-active edge-pod.service
fi
